server:
  port: 8080
#需要使用的配置文件
spring:
  profiles:
    active: test
---

spring:
  profiles: all
  datasource:
    url: jdbc:mysql://10.0.3.136:3306/ts_seq?serverTimezone=GMT&useUnicode=true&characerEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: sinosunts
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.2
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis.pool.max-wait: -1
    # 连接池中的最大空闲连接
    jedis.pool.max-idle: 2
    # 连接超时时间（毫秒）
    timeout: 100
